// Code generated by abstraction-idl from abstraction-resource/resource.thrift. DO NOT EDIT.

// abstraction.resource: declarations for index.mjs.

/** The frame transport a generated client calls: a facade binding or a connector's transport. */
interface FrameTransport {
  exchangeFrame(frame: Uint8Array): Promise<Uint8Array>;
  writeFrame(frame: Uint8Array): Promise<void>;
}

export type AcquireOutcome = (typeof AcquireOutcome)[keyof typeof AcquireOutcome];
export declare const AcquireOutcome: Readonly<{ Acquired: "acquired"; Insufficient: "insufficient"; HoldersRefused: "holders_refused"; NotPermitted: "not_permitted"; Unavailable: "unavailable"; Invalid: "invalid"; Forbidden: "forbidden" }>;

// lease is present exactly for acquired. asked lists every holder the service
// asked to yield for this request, in order, whatever the outcome.
export interface AcquireResult {
  outcome: AcquireOutcome;
  lease: Lease | null;
  asked: YieldRecord[];
}

// answer is present exactly for ok.
export interface AnswerCallResult {
  outcome: ResourceCallOutcome;
  answer: AnswerResult | null;
}

export interface AnswerResult {
  recorded: boolean;
}

export declare class DispatchError extends Error {
  constructor(code: string);
  code: string;
}

export type Evidence = (typeof Evidence)[keyof typeof Evidence];
export declare const Evidence: Readonly<{ Verified: "verified"; Claimed: "claimed" }>;

// program and account are the subject as rights names it: an absolute image
// path or a package family, and a Windows SID or POSIX uid. amount is bytes.
// lease is set when the hold is a lease of lease@1; grant names the rights rule
// it sits under and is empty for a holder that never asked. detail is what the
// holder says it holds, such as a host's model name; it is a claim.
export interface Holder {
  program: string;
  account: string;
  amount: bigint;
  evidence: Evidence;
  lease: string;
  grant: string;
  since: string;
  detail: string;
}

// state is present exactly for ok. A forbidden outcome does not reveal another
// program's rows.
export interface HoldersResult {
  outcome: ResourceCallOutcome;
  state: ResourceState | null;
}

// amount is the requested admission reservation, not a physical memory quota. A
// lease not renewed by renew_by is released; the holder's bytes are then
// reported as a holder without a lease until the instrument stops seeing them.
export interface Lease {
  id: string;
  resource: string;
  amount: bigint;
  since: string;
  renewBy: string;
}

export interface LeaseChange {
  applied: boolean;
  lease: Lease | null;
}

// change is present exactly for ok; applied false retains the idempotent result
// for a lease not held by the caller.
export interface LeaseChangeResult {
  outcome: ResourceCallOutcome;
  change: LeaseChange | null;
}

/** Leases on a scarce resource, asked back on demand. A holder that predates OA is an attached holder: the service yields on its behalf through the host's own mechanism (LM Studio unload, Ollama keep_alive 0, ComfyUI free) and records the result as if answered. Every ask, yield and refusal is a record with the asker, the holder, the amount and the time. Version 1 kills nothing and boosts nothing. */
export declare class LeasesClient {
  constructor(transport: FrameTransport);
  /** Ask to reserve amount bytes for admission of the bound caller, waiting up to wait_ms (0..120000) for holders to yield. The reservation is not a physical usage quota. Order: the rights decision for abstraction.resource/hold on resource (not_permitted, or unavailable when the decision point cannot answer), then the table (insufficient when capacity is known and amount exceeds it), then holders are asked in the service's order and the result is acquired or holders_refused. Nothing is killed. */
  acquire(resource: string, amount: bigint, waitMs: bigint): Promise<AcquireResult>;
  /** Extend renew_by of the bound caller's own lease. */
  renew(lease: string): Promise<LeaseChangeResult>;
  /** End the bound caller's own lease now. */
  release(lease: string): Promise<LeaseChangeResult>;
  /** Yield requests addressed to the bound caller since cursor, waiting up to wait_ms (0..30000) for one. Each request names the lease to yield. A holder that never observes is asked through its adapter when the service has one, and is otherwise recorded as unanswered. */
  observe(cursor: string, waitMs: bigint): Promise<ObserveResult>;
  /** Record the bound caller's answer to one yield request. yielded is checked against the instrument before the asker is told; a refusal carries its reason into the audit. */
  answer(request: string, answer: YieldAnswer, reason: string): Promise<AnswerCallResult>;
  /** Associate the bound caller's own lease with one directly spawned process when its process start identity, parent relation and account can be verified. A failed or unsupported verification returns unverifiable and keeps conservative reservation accounting. One process may bind to one live lease. */
  bindProcess(lease: string, pid: bigint): Promise<ProcessBindResult>;
}

export declare const LeasesService: Readonly<{ wireName: "abstraction.resource/leases@1"; Client: typeof LeasesClient }>;

// page is present exactly for ok.
export interface ObserveResult {
  outcome: ResourceCallOutcome;
  page: YieldPage | null;
}

export type ProcessBindOutcome = (typeof ProcessBindOutcome)[keyof typeof ProcessBindOutcome];
export declare const ProcessBindOutcome: Readonly<{ Bound: "bound"; Unverifiable: "unverifiable"; Refused: "refused"; Invalid: "invalid"; Forbidden: "forbidden"; Unavailable: "unavailable" }>;

// bound permits a verified child process's measured bytes to offset this
// lease's admission reservation. unverifiable and refused leave the full
// reservation in place; no process identity is published in the holder table.
export interface ProcessBindResult {
  outcome: ProcessBindOutcome;
}

export declare class Refusal extends Error {
  constructor(word: string, offset: number);
  word: "malformed" | "bad_string" | "number_spelling" | "wrong_type" | "bad_timestamp" | "depth_exceeded" | "duplicate_key" | "duplicate_field" | "unknown_field" | "missing_field" | "bad_enum" | "trailing_bytes";
  offset: number;
}

export type ResourceCallOutcome = (typeof ResourceCallOutcome)[keyof typeof ResourceCallOutcome];
export declare const ResourceCallOutcome: Readonly<{ Ok: "ok"; Forbidden: "forbidden"; Unavailable: "unavailable"; Invalid: "invalid"; Unknown: "unknown" }>;

export interface ResourceList {
  resources: string[];
  observed: string;
}

// capacity is bytes, 0 when the instrument cannot say. held is the sum of
// verified amounts only. instrument names what measured: windows-gpu-counters,
// linux-fdinfo, or none, in which case every holder is claimed.
export interface ResourceState {
  resource: string;
  capacity: bigint;
  held: bigint;
  holders: Holder[];
  observed: string;
  instrument: string;
}

// list is present exactly for ok.
export interface ResourcesResult {
  outcome: ResourceCallOutcome;
  list: ResourceList | null;
}

export declare class ServiceError extends Error {
  constructor(code: string, message?: string);
  code: string;
}

export type ServiceErrorCode = (typeof ServiceErrorCode)[keyof typeof ServiceErrorCode];
export declare const ServiceErrorCode: Readonly<{ HandlerError: "handler_error"; InvalidResult: "invalid_result"; UnknownVersion: "unknown_version"; UnknownService: "unknown_service"; UnknownMethod: "unknown_method"; WrongMode: "wrong_mode"; Internal: "internal"; InvalidRequest: "invalid_request"; CallerRefused: "caller_refused"; UnknownResource: "unknown_resource"; PolicyUnavailable: "policy_unavailable"; Forbidden: "forbidden" }>;

/** Read-only: who holds how much of a scarce resource on this machine, verified by the instrument or claimed by the holder. No row is invented: a holder the instrument cannot attribute to a program is reported under its process image with evidence verified and no account when the platform gives none. The table changes nothing. */
export declare class TableClient {
  constructor(transport: FrameTransport);
  /** The resources this machine's instrument and adapters can report. */
  resources(): Promise<ResourcesResult>;
  /** Who holds resource now. fresh reads the instrument again; otherwise the last sample within its age bound. Gated by abstraction.resource/table.read on resource account; a program always sees its own rows, and capacity, held and observed describe the machine to every caller. */
  holders(resource: string, fresh: boolean): Promise<HoldersResult>;
}

export declare const TableService: Readonly<{ wireName: "abstraction.resource/table@1"; Client: typeof TableClient }>;

export type YieldAnswer = (typeof YieldAnswer)[keyof typeof YieldAnswer];
export declare const YieldAnswer: Readonly<{ Yielded: "yielded"; Refused: "refused" }>;

export interface YieldPage {
  requests: YieldRequest[];
  next: string;
}

// One holder asked during Acquire: yielded, refused, or unanswered within the
// wait, with the reason a refusal gave.
export interface YieldRecord {
  holder: string;
  amount: bigint;
  answer: string;
  tookMs: bigint;
}

// A request that this holder give back the named lease of amount bytes of
// resource. reason names the program that asked, as rights names it.
export interface YieldRequest {
  id: string;
  resource: string;
  amount: bigint;
  reason: string;
  at: string;
  lease: string;
}

export declare function decode(data: Uint8Array): ResourceState;

export declare function encode(v: ResourceState): Uint8Array;

export declare const knownResources: readonly ["card:0", "memory", "awake"];

export declare function newAcquireResult(): AcquireResult;

export declare function newAnswerCallResult(): AnswerCallResult;

export declare function newAnswerResult(): AnswerResult;

export declare function newHolder(): Holder;

export declare function newHoldersResult(): HoldersResult;

export declare function newLease(): Lease;

export declare function newLeaseChange(): LeaseChange;

export declare function newLeaseChangeResult(): LeaseChangeResult;

export declare function newObserveResult(): ObserveResult;

export declare function newProcessBindResult(): ProcessBindResult;

export declare function newResourceList(): ResourceList;

export declare function newResourceState(): ResourceState;

export declare function newResourcesResult(): ResourcesResult;

export declare function newYieldPage(): YieldPage;

export declare function newYieldRecord(): YieldRecord;

export declare function newYieldRequest(): YieldRequest;

export declare const resourceErrorCodes: readonly ["internal", "invalid_request", "caller_refused", "unknown_resource", "policy_unavailable", "forbidden"];

export {};
