// Code generated by abstraction-idl from abstraction-resource/resource.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function writeList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const Evidence = Object.freeze({
  Verified: "verified",
  Claimed: "claimed",
});

export const ResourceCallOutcome = Object.freeze({
  Ok: "ok",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
  Invalid: "invalid",
  Unknown: "unknown",
});

export const AcquireOutcome = Object.freeze({
  Acquired: "acquired",
  Insufficient: "insufficient",
  HoldersRefused: "holders_refused",
  NotPermitted: "not_permitted",
  Unavailable: "unavailable",
  Invalid: "invalid",
  Forbidden: "forbidden",
});

export const YieldAnswer = Object.freeze({
  Yielded: "yielded",
  Refused: "refused",
});

export const ProcessBindOutcome = Object.freeze({
  Bound: "bound",
  Unverifiable: "unverifiable",
  Refused: "refused",
  Invalid: "invalid",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const ServiceErrorCode = Object.freeze({
  HandlerError: "handler_error",
  InvalidResult: "invalid_result",
  UnknownVersion: "unknown_version",
  UnknownService: "unknown_service",
  UnknownMethod: "unknown_method",
  WrongMode: "wrong_mode",
  Internal: "internal",
  InvalidRequest: "invalid_request",
  CallerRefused: "caller_refused",
  UnknownResource: "unknown_resource",
  PolicyUnavailable: "policy_unavailable",
  Forbidden: "forbidden",
});

export const knownResources = ["card:0", "memory", "awake"];

export const resourceErrorCodes = ["internal", "invalid_request", "caller_refused", "unknown_resource", "policy_unavailable", "forbidden"];

function writeHolder(out, v, depth) {
    if (typeof v.evidence !== "string") throw new Refusal("wrong_type",0);
    if (v.evidence !== "verified" && v.evidence !== "claimed") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "program");
  out.ascii(": ");
  esc(out, v.program);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "account");
  out.ascii(": ");
  esc(out, v.account);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "amount");
  out.ascii(": ");
  num(out, v.amount);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "evidence");
  out.ascii(": ");
  esc(out, v.evidence);
  if (v.lease !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "lease");
    out.ascii(": ");
    esc(out, v.lease);
  }
  if (v.grant !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "grant");
    out.ascii(": ");
    esc(out, v.grant);
  }
  if (v.since !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "since");
    out.ascii(": ");
    esc(out, writeTimestamp(v.since));
  }
  if (v.detail !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "detail");
    out.ascii(": ");
    esc(out, v.detail);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResourceState(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "capacity");
  out.ascii(": ");
  num(out, v.capacity);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "held");
  out.ascii(": ");
  num(out, v.held);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "holders");
  out.ascii(": ");
  writeList(out, v.holders, depth + 1, writeHolder);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "observed");
  out.ascii(": ");
  esc(out, writeTimestamp(v.observed));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "instrument");
  out.ascii(": ");
  esc(out, v.instrument);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeHoldersResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.state !== undefined && v.state !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "state");
    out.ascii(": ");
    writeResourceState(out, v.state, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResourceList(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resources");
  out.ascii(": ");
  strs(out, v.resources, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "observed");
  out.ascii(": ");
  esc(out, writeTimestamp(v.observed));
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResourcesResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.list !== undefined && v.list !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "list");
    out.ascii(": ");
    writeResourceList(out, v.list, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeLease(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "amount");
  out.ascii(": ");
  num(out, v.amount);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "since");
  out.ascii(": ");
  esc(out, writeTimestamp(v.since));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "renew_by");
  out.ascii(": ");
  esc(out, writeTimestamp(v.renewBy));
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeYieldRecord(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "holder");
  out.ascii(": ");
  esc(out, v.holder);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "amount");
  out.ascii(": ");
  num(out, v.amount);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "answer");
  out.ascii(": ");
  esc(out, v.answer);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "took_ms");
  out.ascii(": ");
  num(out, v.tookMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeAcquireResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "acquired" && v.outcome !== "insufficient" && v.outcome !== "holders_refused" && v.outcome !== "not_permitted" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "forbidden") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.lease !== undefined && v.lease !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "lease");
    out.ascii(": ");
    writeLease(out, v.lease, depth + 1);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asked");
  out.ascii(": ");
  writeList(out, v.asked, depth + 1, writeYieldRecord);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeYieldRequest(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "amount");
  out.ascii(": ");
  num(out, v.amount);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "reason");
  out.ascii(": ");
  esc(out, v.reason);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "at");
  out.ascii(": ");
  esc(out, writeTimestamp(v.at));
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "lease");
  out.ascii(": ");
  esc(out, v.lease);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeYieldPage(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "requests");
  out.ascii(": ");
  writeList(out, v.requests, depth + 1, writeYieldRequest);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeObserveResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.page !== undefined && v.page !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "page");
    out.ascii(": ");
    writeYieldPage(out, v.page, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeAnswerResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "recorded");
  out.ascii(": ");
  out.ascii(v.recorded ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeAnswerCallResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.answer !== undefined && v.answer !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "answer");
    out.ascii(": ");
    writeAnswerResult(out, v.answer, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeLeaseChange(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "applied");
  out.ascii(": ");
  out.ascii(v.applied ? "true" : "false");
  if (v.lease !== undefined && v.lease !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "lease");
    out.ascii(": ");
    writeLease(out, v.lease, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeLeaseChangeResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.change !== undefined && v.change !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "change");
    out.ascii(": ");
    writeLeaseChange(out, v.change, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeProcessBindResult(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "bound" && v.outcome !== "unverifiable" && v.outcome !== "refused" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOATableResourcesArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x7d);
}

function writeOATableHoldersArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "fresh");
  out.ascii(": ");
  out.ascii(v.fresh ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesAcquireArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "resource");
  out.ascii(": ");
  esc(out, v.resource);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "amount");
  out.ascii(": ");
  num(out, v.amount);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.waitMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesRenewArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "lease");
  out.ascii(": ");
  esc(out, v.lease);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesReleaseArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "lease");
  out.ascii(": ");
  esc(out, v.lease);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesObserveArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.waitMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesAnswerArguments(out, v, depth) {
    if (typeof v.answer !== "string") throw new Refusal("wrong_type",0);
    if (v.answer !== "yielded" && v.answer !== "refused") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request");
  out.ascii(": ");
  esc(out, v.request);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "answer");
  out.ascii(": ");
  esc(out, v.answer);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "reason");
  out.ascii(": ");
  esc(out, v.reason);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesBindProcessArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "lease");
  out.ascii(": ");
  esc(out, v.lease);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "pid");
  out.ascii(": ");
  num(out, v.pid);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceFrame(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceReply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceError(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOATableResourcesResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeResourcesResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOATableHoldersResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeHoldersResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesAcquireResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeAcquireResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesRenewResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeLeaseChangeResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesReleaseResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeLeaseChangeResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesObserveResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeObserveResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesAnswerResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeAnswerCallResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOALeasesBindProcessResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeProcessBindResult(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeResourceState(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function readList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

const isDigits = (s, i, n) => {
  if (s.length < i + n) return false;
  for (let k = 0; k < n; k++) if (s[i + k] < "0" || s[i + k] > "9") return false;
  return true;
};

const datePart = (s) =>
  s.length >= 19 && isDigits(s, 0, 4) && s[4] === "-" && isDigits(s, 5, 2) && s[7] === "-" &&
  isDigits(s, 8, 2) && isDigits(s, 11, 2) && s[13] === ":" && isDigits(s, 14, 2) && s[16] === ":" &&
  isDigits(s, 17, 2);

// [DEF-G1] rfc3339-wide: what a reader accepts. Any fraction of one to nine
// digits or none, either case of the separators, and a numeric offset.
function lexicalTimestamp(s) {
  if (!datePart(s) || (s[10] !== "T" && s[10] !== "t")) return false;
  let i = 19;
  if (i < s.length && s[i] === ".") {
    i++;
    const start = i;
    while (i < s.length && s[i] >= "0" && s[i] <= "9") i++;
    if (i - start < 1 || i - start > 9) return false;
  }
  if (i >= s.length) return false;
  if (s[i] === "Z" || s[i] === "z") return i + 1 === s.length;
  if (s[i] !== "+" && s[i] !== "-") return false;
  return s.length === i + 6 && isDigits(s, i + 1, 2) && s[i + 3] === ":" && isDigits(s, i + 4, 2);
}

// [DEF-G2] rfc3339-micros: what a writer emits. Exactly six fractional digits,
// upper-case separators, UTC.
export function microsTimestamp(s) {
  return s.length === 27 && normalizedTimestamp(s) === s;
}

function readTimestamp(r) {
  const at = r.pos;
  const s = r.string();
  if (!wideTimestamp(s)) {
    r.pos = at;
    throw r.refuse("bad_timestamp");
  }
  return s;
}

function timestampDays(y, m) {
  if (m === 2) return y % 4 === 0 && (y % 100 !== 0 || y % 400 === 0) ? 29 : 28;
  return [4, 6, 9, 11].includes(m) ? 30 : 31;
}
function normalizedTimestamp(s) {
  if (!lexicalTimestamp(s)) return "";
  let y=Number(s.slice(0,4)), m=Number(s.slice(5,7)), d=Number(s.slice(8,10));
  const h=Number(s.slice(11,13)), minute=Number(s.slice(14,16)), sec=Number(s.slice(17,19));
  if (m<1 || m>12 || d<1 || d>timestampDays(y,m) || h>23 || minute>59 || sec>59) return "";
  let i=19, fraction="";
  if (s[i]===".") { const start=++i; while(s[i]>="0" && s[i]<="9") i++; fraction=s.slice(start,i); }
  let total=h*60+minute;
  if(s[i]==="+" || s[i]==="-") {
    const oh=Number(s.slice(i+1,i+3)), om=Number(s.slice(i+4,i+6));
    if(oh>23 || om>59) return "";
    total += (s[i]==="+" ? -1 : 1)*(oh*60+om);
  }
  if(total<0) {total+=1440; d--;} else if(total>=1440) {total-=1440; d++;}
  if(d===0) {m--; if(m===0) {y--; m=12;} d=timestampDays(y,m);}
  if(d>timestampDays(y,m)) {d=1; m++; if(m===13) {y++; m=1;}}
  if(y<0 || y>9999) return "";
  const pad=(n,w)=>String(n).padStart(w,"0");
  return pad(y,4)+"-"+pad(m,2)+"-"+pad(d,2)+"T"+pad(Math.floor(total/60),2)+":"+pad(total%60,2)+":"+pad(sec,2)+"."+(fraction+"000000").slice(0,6)+"Z";
}
export function wideTimestamp(s) { return normalizedTimestamp(s)!==""; }
function writeTimestamp(s) {
  const result=normalizedTimestamp(s);
  if(result==="") throw new Refusal("bad_timestamp",0);
  return result;
}

// program and account are the subject as rights names it: an absolute image
// path or a package family, and a Windows SID or POSIX uid. amount is bytes.
// lease is set when the hold is a lease of lease@1; grant names the rights rule
// it sits under and is empty for a holder that never asked. detail is what the
// holder says it holds, such as a host's model name; it is a claim.
export function newHolder() {
  return { program: "", account: "", amount: 0n, evidence: "", lease: "", grant: "", since: "", detail: "" };
}

// capacity is bytes, 0 when the instrument cannot say. held is the sum of
// verified amounts only. instrument names what measured: windows-gpu-counters,
// linux-fdinfo, or none, in which case every holder is claimed.
export function newResourceState() {
  return { resource: "", capacity: 0n, held: 0n, holders: [], observed: "", instrument: "" };
}

// state is present exactly for ok. A forbidden outcome does not reveal another
// program's rows.
export function newHoldersResult() {
  return { outcome: "", state: null };
}

export function newResourceList() {
  return { resources: [], observed: "" };
}

// list is present exactly for ok.
export function newResourcesResult() {
  return { outcome: "", list: null };
}

// amount is the requested admission reservation, not a physical memory quota. A
// lease not renewed by renew_by is released; the holder's bytes are then
// reported as a holder without a lease until the instrument stops seeing them.
export function newLease() {
  return { id: "", resource: "", amount: 0n, since: "", renewBy: "" };
}

// One holder asked during Acquire: yielded, refused, or unanswered within the
// wait, with the reason a refusal gave.
export function newYieldRecord() {
  return { holder: "", amount: 0n, answer: "", tookMs: 0n };
}

// lease is present exactly for acquired. asked lists every holder the service
// asked to yield for this request, in order, whatever the outcome.
export function newAcquireResult() {
  return { outcome: "", lease: null, asked: [] };
}

// A request that this holder give back the named lease of amount bytes of
// resource. reason names the program that asked, as rights names it.
export function newYieldRequest() {
  return { id: "", resource: "", amount: 0n, reason: "", at: "", lease: "" };
}

export function newYieldPage() {
  return { requests: [], next: "" };
}

// page is present exactly for ok.
export function newObserveResult() {
  return { outcome: "", page: null };
}

export function newAnswerResult() {
  return { recorded: false };
}

// answer is present exactly for ok.
export function newAnswerCallResult() {
  return { outcome: "", answer: null };
}

export function newLeaseChange() {
  return { applied: false, lease: null };
}

// change is present exactly for ok; applied false retains the idempotent result
// for a lease not held by the caller.
export function newLeaseChangeResult() {
  return { outcome: "", change: null };
}

// bound permits a verified child process's measured bytes to offset this
// lease's admission reservation. unverifiable and refused leave the full
// reservation in place; no process identity is published in the holder table.
export function newProcessBindResult() {
  return { outcome: "" };
}

function newOATableResourcesArguments() {
  return { };
}

function newOATableHoldersArguments() {
  return { resource: "", fresh: false };
}

function newOALeasesAcquireArguments() {
  return { resource: "", amount: 0n, waitMs: 0n };
}

function newOALeasesRenewArguments() {
  return { lease: "" };
}

function newOALeasesReleaseArguments() {
  return { lease: "" };
}

function newOALeasesObserveArguments() {
  return { cursor: "", waitMs: 0n };
}

function newOALeasesAnswerArguments() {
  return { request: "", answer: "", reason: "" };
}

function newOALeasesBindProcessArguments() {
  return { lease: "", pid: 0n };
}

function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

function newOAServiceError() {
  return { code: "", message: "" };
}

function newOATableResourcesResult() {
  return { value: newResourcesResult() };
}

function newOATableHoldersResult() {
  return { value: newHoldersResult() };
}

function newOALeasesAcquireResult() {
  return { value: newAcquireResult() };
}

function newOALeasesRenewResult() {
  return { value: newLeaseChangeResult() };
}

function newOALeasesReleaseResult() {
  return { value: newLeaseChangeResult() };
}

function newOALeasesObserveResult() {
  return { value: newObserveResult() };
}

function newOALeasesAnswerResult() {
  return { value: newAnswerCallResult() };
}

function newOALeasesBindProcessResult() {
  return { value: newProcessBindResult() };
}

function readHolder(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHolder();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "program") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.program = r.string();
      } else if (key === "account") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.account = r.string();
      } else if (key === "amount") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.amount = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "evidence") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.evidence = r.string();
      } else if (key === "lease") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.lease = r.string();
      } else if (key === "grant") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.grant = r.string();
      } else if (key === "since") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.since = readTimestamp(r);
      } else if (key === "detail") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.detail = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.evidence !== "verified" && v.evidence !== "claimed") { throw r.refuse("bad_enum"); }
  return v;
}

function readResourceState(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResourceState();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "resource") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.resource = r.string();
      } else if (key === "capacity") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.capacity = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "held") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.held = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "holders") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.holders = readList(r, readHolder);
      } else if (key === "observed") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.observed = readTimestamp(r);
      } else if (key === "instrument") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.instrument = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 63) >>> 0) !== 63) throw r.refuse("missing_field");
  return v;
}

function readHoldersResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newHoldersResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "state") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.state = readResourceState(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readResourceList(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResourceList();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "resources") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.resources = r.strList();
      } else if (key === "observed") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.observed = readTimestamp(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readResourcesResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResourcesResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "list") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.list = readResourceList(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readLease(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newLease();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "resource") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.resource = r.string();
      } else if (key === "amount") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.amount = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "since") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.since = readTimestamp(r);
      } else if (key === "renew_by") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.renewBy = readTimestamp(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readYieldRecord(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newYieldRecord();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "holder") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.holder = r.string();
      } else if (key === "amount") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.amount = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "answer") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.answer = r.string();
      } else if (key === "took_ms") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.tookMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readAcquireResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAcquireResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "lease") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.lease = readLease(r);
      } else if (key === "asked") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.asked = readList(r, readYieldRecord);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 5) >>> 0) !== 5) throw r.refuse("missing_field");
    if (v.outcome !== "acquired" && v.outcome !== "insufficient" && v.outcome !== "holders_refused" && v.outcome !== "not_permitted" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "forbidden") { throw r.refuse("bad_enum"); }
  return v;
}

function readYieldRequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newYieldRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "resource") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.resource = r.string();
      } else if (key === "amount") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.amount = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "reason") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.reason = r.string();
      } else if (key === "at") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.at = readTimestamp(r);
      } else if (key === "lease") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.lease = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 63) >>> 0) !== 63) throw r.refuse("missing_field");
  return v;
}

function readYieldPage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newYieldPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "requests") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.requests = readList(r, readYieldRequest);
      } else if (key === "next") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.next = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readObserveResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "page") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.page = readYieldPage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readAnswerResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAnswerResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "recorded") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.recorded = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readAnswerCallResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAnswerCallResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "answer") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.answer = readAnswerResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readLeaseChange(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newLeaseChange();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "applied") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.applied = r.boolean();
      } else if (key === "lease") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.lease = readLease(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readLeaseChangeResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newLeaseChangeResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "change") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.change = readLeaseChange(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "ok" && v.outcome !== "forbidden" && v.outcome !== "unavailable" && v.outcome !== "invalid" && v.outcome !== "unknown") { throw r.refuse("bad_enum"); }
  return v;
}

function readProcessBindResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newProcessBindResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "bound" && v.outcome !== "unverifiable" && v.outcome !== "refused" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOATableResourcesArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOATableResourcesArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (false) {
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function readOATableHoldersArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOATableHoldersArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "resource") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.resource = r.string();
      } else if (key === "fresh") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.fresh = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOALeasesAcquireArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesAcquireArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "resource") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.resource = r.string();
      } else if (key === "amount") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.amount = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else if (key === "wait_ms") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.waitMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function readOALeasesRenewArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesRenewArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "lease") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.lease = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesReleaseArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesReleaseArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "lease") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.lease = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesObserveArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesObserveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "wait_ms") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.waitMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOALeasesAnswerArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesAnswerArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.request = r.string();
      } else if (key === "answer") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.answer = r.string();
      } else if (key === "reason") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.reason = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
    if (v.answer !== "yielded" && v.answer !== "refused") { throw r.refuse("bad_enum"); }
  return v;
}

function readOALeasesBindProcessArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesBindProcessArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "lease") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.lease = r.string();
      } else if (key === "pid") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.pid = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAServiceFrame(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readOAServiceReply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readOAServiceError(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOATableResourcesResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOATableResourcesResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readResourcesResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOATableHoldersResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOATableHoldersResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readHoldersResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesAcquireResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesAcquireResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readAcquireResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesRenewResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesRenewResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readLeaseChangeResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesReleaseResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesReleaseResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readLeaseChangeResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesObserveResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readObserveResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesAnswerResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesAnswerResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readAnswerCallResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOALeasesBindProcessResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOALeasesBindProcessResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readProcessBindResult(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readResourceState(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "bad_timestamp", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["Holder"] = [["program","string","never"],["account","string","never"],["amount","i64","never"],["evidence","string","never"],["lease","string","zero"],["grant","string","zero"],["since","string","zero"],["detail","string","zero"],];
_serviceRecords["ResourceState"] = [["resource","string","never"],["capacity","i64","never"],["held","i64","never"],["holders","list<Holder>","never"],["observed","string","never"],["instrument","string","never"],];
_serviceRecords["HoldersResult"] = [["outcome","string","never"],["state","ResourceState","absent"],];
_serviceRecords["ResourceList"] = [["resources","list<string>","never"],["observed","string","never"],];
_serviceRecords["ResourcesResult"] = [["outcome","string","never"],["list","ResourceList","absent"],];
_serviceRecords["Lease"] = [["id","string","never"],["resource","string","never"],["amount","i64","never"],["since","string","never"],["renewBy","string","never"],];
_serviceRecords["YieldRecord"] = [["holder","string","never"],["amount","i64","never"],["answer","string","never"],["tookMs","i64","never"],];
_serviceRecords["AcquireResult"] = [["outcome","string","never"],["lease","Lease","absent"],["asked","list<YieldRecord>","never"],];
_serviceRecords["YieldRequest"] = [["id","string","never"],["resource","string","never"],["amount","i64","never"],["reason","string","never"],["at","string","never"],["lease","string","never"],];
_serviceRecords["YieldPage"] = [["requests","list<YieldRequest>","never"],["next","string","never"],];
_serviceRecords["ObserveResult"] = [["outcome","string","never"],["page","YieldPage","absent"],];
_serviceRecords["AnswerResult"] = [["recorded","bool","never"],];
_serviceRecords["AnswerCallResult"] = [["outcome","string","never"],["answer","AnswerResult","absent"],];
_serviceRecords["LeaseChange"] = [["applied","bool","never"],["lease","Lease","absent"],];
_serviceRecords["LeaseChangeResult"] = [["outcome","string","never"],["change","LeaseChange","absent"],];
_serviceRecords["ProcessBindResult"] = [["outcome","string","never"],];
_serviceRecords["OATableResourcesArguments"] = [];
_serviceRecords["OATableHoldersArguments"] = [["resource","string","never"],["fresh","bool","never"],];
_serviceRecords["OALeasesAcquireArguments"] = [["resource","string","never"],["amount","i64","never"],["waitMs","i64","never"],];
_serviceRecords["OALeasesRenewArguments"] = [["lease","string","never"],];
_serviceRecords["OALeasesReleaseArguments"] = [["lease","string","never"],];
_serviceRecords["OALeasesObserveArguments"] = [["cursor","string","never"],["waitMs","i64","never"],];
_serviceRecords["OALeasesAnswerArguments"] = [["request","string","never"],["answer","string","never"],["reason","string","never"],];
_serviceRecords["OALeasesBindProcessArguments"] = [["lease","string","never"],["pid","i64","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OATableResourcesResult"] = [["value","ResourcesResult","never"],];
_serviceRecords["OATableHoldersResult"] = [["value","HoldersResult","never"],];
_serviceRecords["OALeasesAcquireResult"] = [["value","AcquireResult","never"],];
_serviceRecords["OALeasesRenewResult"] = [["value","LeaseChangeResult","never"],];
_serviceRecords["OALeasesReleaseResult"] = [["value","LeaseChangeResult","never"],];
_serviceRecords["OALeasesObserveResult"] = [["value","ObserveResult","never"],];
_serviceRecords["OALeasesAnswerResult"] = [["value","AnswerCallResult","never"],];
_serviceRecords["OALeasesBindProcessResult"] = [["value","ProcessBindResult","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(writeOAServiceFrame, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(readOAServiceReply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(readOAServiceError, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class TableClient {
  constructor(transport) { this._transport = transport; }

  async resources() {
    const _args = newOATableResourcesArguments();
    _serviceCheck("OATableResourcesArguments", _args);
    const _payload = _serviceEncode(writeOATableResourcesArguments, _args, 1);
    _serviceDecode(readOATableResourcesArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/table@1", "Resources", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/table@1", "Resources");
    const _result = _serviceDecode(readOATableResourcesResult, _reply, 1);
    return _result.value;
  }

  async holders(resource, fresh) {
    const _args = newOATableHoldersArguments();
    _args.resource = resource;
    _args.fresh = fresh;
    _serviceCheck("OATableHoldersArguments", _args);
    const _payload = _serviceEncode(writeOATableHoldersArguments, _args, 1);
    _serviceDecode(readOATableHoldersArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/table@1", "Holders", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/table@1", "Holders");
    const _result = _serviceDecode(readOATableHoldersResult, _reply, 1);
    return _result.value;
  }
}
export const TableService = Object.freeze({wireName:"abstraction.resource/table@1",Client:TableClient});

export class LeasesClient {
  constructor(transport) { this._transport = transport; }

  async acquire(resource, amount, waitMs) {
    const _args = newOALeasesAcquireArguments();
    _args.resource = resource;
    _args.amount = amount;
    _args.waitMs = waitMs;
    _serviceCheck("OALeasesAcquireArguments", _args);
    const _payload = _serviceEncode(writeOALeasesAcquireArguments, _args, 1);
    _serviceDecode(readOALeasesAcquireArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "Acquire", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "Acquire");
    const _result = _serviceDecode(readOALeasesAcquireResult, _reply, 1);
    return _result.value;
  }

  async renew(lease) {
    const _args = newOALeasesRenewArguments();
    _args.lease = lease;
    _serviceCheck("OALeasesRenewArguments", _args);
    const _payload = _serviceEncode(writeOALeasesRenewArguments, _args, 1);
    _serviceDecode(readOALeasesRenewArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "Renew", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "Renew");
    const _result = _serviceDecode(readOALeasesRenewResult, _reply, 1);
    return _result.value;
  }

  async release(lease) {
    const _args = newOALeasesReleaseArguments();
    _args.lease = lease;
    _serviceCheck("OALeasesReleaseArguments", _args);
    const _payload = _serviceEncode(writeOALeasesReleaseArguments, _args, 1);
    _serviceDecode(readOALeasesReleaseArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "Release", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "Release");
    const _result = _serviceDecode(readOALeasesReleaseResult, _reply, 1);
    return _result.value;
  }

  async observe(cursor, waitMs) {
    const _args = newOALeasesObserveArguments();
    _args.cursor = cursor;
    _args.waitMs = waitMs;
    _serviceCheck("OALeasesObserveArguments", _args);
    const _payload = _serviceEncode(writeOALeasesObserveArguments, _args, 1);
    _serviceDecode(readOALeasesObserveArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "Observe", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "Observe");
    const _result = _serviceDecode(readOALeasesObserveResult, _reply, 1);
    return _result.value;
  }

  async answer(request, answer, reason) {
    const _args = newOALeasesAnswerArguments();
    _args.request = request;
    _args.answer = answer;
    _args.reason = reason;
    _serviceCheck("OALeasesAnswerArguments", _args);
    const _payload = _serviceEncode(writeOALeasesAnswerArguments, _args, 1);
    _serviceDecode(readOALeasesAnswerArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "Answer", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "Answer");
    const _result = _serviceDecode(readOALeasesAnswerResult, _reply, 1);
    return _result.value;
  }

  async bindProcess(lease, pid) {
    const _args = newOALeasesBindProcessArguments();
    _args.lease = lease;
    _args.pid = pid;
    _serviceCheck("OALeasesBindProcessArguments", _args);
    const _payload = _serviceEncode(writeOALeasesBindProcessArguments, _args, 1);
    _serviceDecode(readOALeasesBindProcessArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.resource/leases@1", "BindProcess", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.resource/leases@1", "BindProcess");
    const _result = _serviceDecode(readOALeasesBindProcessResult, _reply, 1);
    return _result.value;
  }
}
export const LeasesService = Object.freeze({wireName:"abstraction.resource/leases@1",Client:LeasesClient});
